SOURCES = redblack.mli redblack.ml station_name.ml station_connection.ml station_connection_tree.ml station.ml station_name_sort.ml station_distance.ml station_update.ml station_separate.ml dijkstra.ml main.ml
RESULT = metro_network
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)
